#!/usr/bin/env python3
"""Generate src/ca_bundle.h: a small root-CA bundle for verifying HTTPS blocklist downloads.

The framework ships Mozilla's full bundle (~63 KB), which doesn't fit the ~75 KB left in
the dual-OTA app slot. This picks the roots behind GitHub's download hosts plus the other
big public CAs (Let's Encrypt, Sectigo, DigiCert, Google, GlobalSign, Amazon), so most
HTTPS hosts work, and writes them in the format WiFiClientSecure::setCACertBundle() reads
(same as ESP-IDF's gen_crt_bundle.py):

  u16 count, then per cert sorted by subject DER: u16 name_len, u16 key_len, subject DER,
  SubjectPublicKeyInfo DER   (all big-endian)

Usage: gen_ca_bundle.py [cacert.pem] [out.h]
  cacert.pem defaults to certifi's Mozilla bundle (pip install certifi).
"""
import base64
import re
import sys

# Matched against the "# Label:" line that precedes each cert in Mozilla/certifi PEM files.
ROOTS = [
    'ISRG Root X1', 'ISRG Root X2',                               # Let's Encrypt (GitHub asset CDN)
    'USERTrust RSA Certification Authority',                      # Sectigo (github.com)
    'USERTrust ECC Certification Authority',
    'Sectigo Public Server Authentication Root R46',
    'Sectigo Public Server Authentication Root E46',
    'DigiCert Global Root G2', 'DigiCert Global Root G3',
    'GTS Root R1', 'GTS Root R3', 'GTS Root R4',                  # Google / Cloudflare
    'GlobalSign Root CA - R3', 'GlobalSign Root R46', 'GlobalSign Root E46',
    'Amazon Root CA 1', 'Amazon Root CA 3',                       # S3 / CloudFront
]


def der_tlv(buf, pos):
    """Return (tag, header_len, content_len) of the DER element at pos."""
    tag = buf[pos]
    n = buf[pos + 1]
    if n < 0x80:
        return tag, 2, n
    k = n & 0x7F
    return tag, 2 + k, int.from_bytes(buf[pos + 2:pos + 2 + k], 'big')


def children(buf, pos):
    """Yield (start, end) of each element inside the constructed element at pos."""
    _, hl, cl = der_tlv(buf, pos)
    p, end = pos + hl, pos + hl + cl
    while p < end:
        _, h, c = der_tlv(buf, p)
        yield p, p + h + c
        p += h + c


def subject_and_spki(der):
    tbs_start, _ = next(children(der, 0))                         # Certificate -> tbsCertificate
    fields = list(children(der, tbs_start))
    if der[fields[0][0]] == 0xA0:                                 # optional [0] version
        fields = fields[1:]
    # serialNumber, signature, issuer, validity, subject, subjectPublicKeyInfo
    (ss, se), (ks, ke) = fields[4], fields[5]
    return der[ss:se], der[ks:ke]


def load_pem(path):
    certs, label = {}, None
    text = open(path, encoding='utf-8').read()
    for m in re.finditer(r'^# Label: "([^"]+)"$|-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----',
                         text, re.M | re.S):
        if m.group(1):
            label = m.group(1)
        elif label:
            certs[label] = base64.b64decode(''.join(m.group(2).split()))
            label = None
    return certs


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    if not src:
        import certifi
        src = certifi.where()
    out = sys.argv[2] if len(sys.argv) > 2 else 'src/ca_bundle.h'

    certs = load_pem(src)
    missing = [r for r in ROOTS if r not in certs]
    if missing:
        sys.exit(f'missing from {src}: {missing}')

    entries = sorted(subject_and_spki(certs[r]) for r in ROOTS)   # binary-searched by subject
    blob = len(entries).to_bytes(2, 'big')
    for name, key in entries:
        blob += len(name).to_bytes(2, 'big') + len(key).to_bytes(2, 'big') + name + key

    lines = [', '.join(f'0x{b:02x}' for b in blob[i:i + 16]) for i in range(0, len(blob), 16)]
    with open(out, 'w') as f:
        f.write('#pragma once\n'
                '// Generated by tools/gen_ca_bundle.py -- do not edit. Root CAs trusted for HTTPS\n'
                '// blocklist downloads:\n')
        for r in ROOTS:
            f.write(f'//   {r}\n')
        f.write(f'static const uint8_t CA_BUNDLE[{len(blob)}] = {{\n  ' + ',\n  '.join(lines) + '\n};\n')
    print(f'{len(entries)} roots, {len(blob)} bytes -> {out}')


if __name__ == '__main__':
    main()
